# Generated by Django 4.1 on 2022-10-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField(blank=True, null=True)),
                ('apellido_paterno', models.TextField(blank=True, null=True)),
                ('apellido_materno', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tel_movil', models.IntegerField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('correo_e', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('fecha_caducidad', models.DateTimeField(null=True)),
                ('estado_actual', models.FloatField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('disponibilidad', models.FloatField(blank=True, null=True)),
                ('en_promocion', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField(blank=True, null=True)),
                ('apellido_paterno', models.TextField(blank=True, null=True)),
                ('apellido_materno', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rfc', models.TextField(blank=True, null=True)),
                ('nombre_comercio', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('tel_fijo', models.IntegerField(blank=True, null=True)),
                ('tel_movil', models.IntegerField(blank=True, null=True)),
                ('horario_laboral', models.TextField(blank=True, null=True)),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('correo_e', models.TextField(blank=True, null=True)),
                ('calificacion', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_apartado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_apartado', models.DateTimeField(null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.comprador')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.producto')),
                ('vendedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vendedor'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comprador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.comprador')),
                ('mensaje_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mensaje')),
                ('vendedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vendedor')),
            ],
        ),
    ]
