# Generated by Django 4.1 on 2022-10-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_comprador_id_chat_comprador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_apartado',
            name='tiempo_apartado',
            field=models.TimeField(null=True),
        ),
    ]
